apiVersion: v1
kind: Secret
metadata:
  name: ipp-platform-claims-gitea
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: http://gitea.gitea.svc.cluster.local:3000/ipp-automation-bot/ipp-platform-claims
  username: ipp-automation-bot
  password: ipp-bot-demo-2024
  forceHttpBasicAuth: "true"
  insecure: "true"
