apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ipp-platform
    app.kubernetes.io/component: app-of-apps
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amitabhmanish13/IPP_Demoselfservice.git
    targetRevision: main
    path: gitops/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 5
